# filename - custom_conditional_build_config

version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Image
          command: |
            if [[ -n $(git diff --name-only $CIRCLE_SHA1 $CIRCLE_SHA1^ | grep "src-1/") ]]; then
              # Changes detected in src-1 directory
              TAG=src-1-0.1.$CIRCLE_BUILD_NUM
              IMAGE_NAME=$DOCKER_USER/django-app-circleci-src-1:$TAG
              docker build -t $IMAGE_NAME src-1
            elif [[ -n $(git diff --name-only $CIRCLE_SHA1 $CIRCLE_SHA1^ | grep "src-2/") ]]; then
              # Changes detected in src-2 directory
              TAG=src-2-0.1.$CIRCLE_BUILD_NUM
              IMAGE_NAME=$DOCKER_USER/django-app-circleci-src-2:$TAG
              docker build -t $IMAGE_NAME src-2
            else
              echo "No relevant changes detected in src-1 or src-2, skipping the build."
              exit 0
            fi

            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME

workflows:
  build_push_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - main  
