version: 2.1

executors:
  my_executor:
    docker:
      - image: cimg/python:3.12.0

jobs:
  build:
    executor: my_executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            IMAGE_NAME=$DOCKER_USER/django-app-circleci:$TAG
            docker build -t $IMAGE_NAME .
  
  push:
    executor: my_executor
    steps:
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            TAG=0.1.$CIRCLE_BUILD_NUM
            IMAGE_NAME=$DOCKER_USER/django-app-circleci:$TAG
            docker push $IMAGE_NAME
  
  deploy:
    executor: my_executor
    steps:
      - run:
          name: Deploy
          command: |
            # Todo

workflows:
  build_push_and_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push
